"""Every sentence a human reads during a check or an install, pulled out of the scripts.

Two of four beta testers read Spanish first. Before anything can be translated, somebody has to be able
to see the whole set — and the set lives inside printf format strings in two large shell scripts, where
it is neither countable nor reviewable.

This walks tools/preflight.sh and install.sh, lifts every literal a human sees, strips the format
specifiers and colour variables, and writes data/strings/en.yml: the English inventory, keyed by file and
line, with the count. It does NOT translate anything and it does not rewrite the scripts.

  python3 tools/extract_strings.py            write data/strings/en.yml
  python3 tools/extract_strings.py --check    fail if the inventory is stale (make lint runs this)
"""
import re
import sys

SOURCES = ("tools/preflight.sh", "install.sh")
OUT = "data/strings/en.yml"

# printf 'FORMAT' ... / echo "TEXT" — the first quoted argument is what a person reads.
PAT = re.compile(r"""(?:printf|echo|say|warn|die|step)\s+(?:-e\s+)?(['"])(.+?)(?<!\\)\1""")
NOISE = re.compile(r"""\\033\[[0-9;]*m|%-?[0-9.]*[sdif]|\$\{?[A-Za-z_][A-Za-z0-9_]*\}?|\\n|\\t|%%|\$\(.*?\)""")


def strings() -> list[tuple[str, int, str]]:
    found = []
    for src in SOURCES:
        for n, line in enumerate(open(src), 1):
            if line.lstrip().startswith("#"):
                continue
            for _, raw in PAT.findall(line):
                text = " ".join(NOISE.sub(" ", raw).split())
                text = text.strip(" |·-—:")
                # keep what a person READS. A command is not prose: it is the same in every language,
                # and translating it would break it. JSON templates are not prose either.
                if len(text) < 12 or " " not in text or not re.search("[A-Za-z]", text):
                    continue
                if any(t in text for t in ('{"', "&&", "http", "| bash", "$(", "sudo ", "docker ", "curl ")):
                    continue
                if re.match(r"^[a-z_]+\s+-", text):        # a flagged command, e.g. `tar xzf -C`
                    continue
                found.append((src, n, text))
    return found


def render(found: list[tuple[str, int, str]]) -> str:
    head = [
        "# The English strings a person reads during `planetai preflight` and an install.",
        "#",
        "# Generated by tools/extract_strings.py — the inventory, not the source. Editing this file does",
        "# not change what the scripts print; it exists so the whole set can be SEEN before any of it is",
        "# translated. Two of four beta testers read Spanish first.",
        "#",
        "# A Spanish set belongs beside this one as es.yml, written by a person who speaks it. Nothing here",
        "# was machine-translated and nothing here should be.",
        "#",
        f"# {len(found)} strings from {', '.join(SOURCES)}.",
        "",
        "strings:",
    ]
    for src, n, text in found:
        esc = text.replace('"', '\\"')
        head.append(f'  - key: {src.replace("/", "_").replace(".sh", "")}:{n}')
        head.append(f'    en: "{esc}"')
    return "\n".join(head) + "\n"


want = render(strings())
if "--check" in sys.argv:
    try:
        have = open(OUT).read()
    except FileNotFoundError:
        sys.exit(f"  x {OUT} does not exist. Run: python3 tools/extract_strings.py")
    if have != want:
        sys.exit(f"  x {OUT} is stale — a user-facing string changed. Run: python3 tools/extract_strings.py")
    print(f"  {want.count(chr(10)) // 2} strings inventoried in {OUT}")
    sys.exit(0)

import os
os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, "w").write(want)
print(f"  wrote {OUT}")
