#!/usr/bin/env python3
"""What a fresh node gets for every key, written where the container can read it.

    python3 tools/gen_defaults.py            rewrite data/env_defaults.yml
    python3 tools/gen_defaults.py --check    fail if it is stale (make lint runs this)

`.env.example` is this repo's record of what a key defaults to, and it is already held to a rule by
`make lint` (comments above their keys, never after). It is also at the repo root — and the app
image is built from `app/`, so a COPY cannot reach it and the container has never been able to say
what a default IS. It could only say, via `source`, that the value it holds happens to be one.

So this generates the same facts into `data/`, which IS mounted read-only into the image, beside
the source registry and the platform floors. Same shape as tools/gen_floors.py: one authority, one
generated copy, and a --check in lint so the two cannot drift. The authority stays `.env.example`,
because that is the file a person edits when they change what a node ships with.

Nothing secret travels: `.env.example` is the example, its token and key lines are blank, and this
carries only what is already committed in it.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC, OUT = ROOT / ".env.example", ROOT / "data" / "env_defaults.yml"
HEAD = ("# GENERATED by tools/gen_defaults.py from .env.example — do not edit.\n"
        "# What a fresh node gets for each key, and the comment above it, so a container that\n"
        "# cannot read .env.example (the app image is built from app/) can still say what a\n"
        "# default is. `make lint` fails when this and .env.example disagree.\n")


def read(text: str) -> list[tuple[str, str, str]]:
    """[(KEY, default, help)] — comments above a key describe it, and a blank line ends a block.

    A run of keys under one comment all take it: `.env.example` is written that way in places, and
    so are the packs' own `env:` blocks, which app/settings.py reads with the same rule.
    """
    out: list[tuple[str, str, str]] = []
    note: list[str] = []
    started = False
    for raw in text.splitlines():
        s = raw.strip()
        if s.startswith("#"):
            if started:
                note, started = [], False
            line = s.lstrip("#").strip()
            # `---- who and where ----` is a section divider, not a sentence about the next key.
            if line and set(line) - set("- ="):
                note.append(line)
            continue
        if "=" not in s:
            note, started = [], False
            continue
        key, _, rest = s.partition("=")
        key = key.strip()
        if not (key and key.isupper() and key.replace("_", "").isalnum()):
            note, started = [], False
            continue
        # `.env.example` puts an inline comment after some values; it is help, not value.
        value, _, trailing = rest.partition("#")
        help_ = " ".join(n for n in note if n)
        if trailing.strip():
            help_ = (help_ + " " + trailing.strip()).strip()
        out.append((key, value.strip(), help_))
        started = True
    return out


def render(rows: list[tuple[str, str, str]]) -> str:
    def q(s: str) -> str:
        return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'
    body = "".join(f"{k}:\n  default: {q(v)}\n  help: {q(h)}\n" for k, v, h in rows)
    return HEAD + body


def main(argv: list[str]) -> int:
    if not SRC.is_file():
        print(f"  x {SRC.name} is missing, so there is nothing to generate from")
        return 1
    want = render(read(SRC.read_text()))
    check = "--check" in argv
    have = OUT.read_text() if OUT.is_file() else ""
    if check:
        if have != want:
            n = len(read(SRC.read_text()))
            print(f"  x data/{OUT.name} is stale against .env.example ({n} keys there). "
                  f"Run: python3 tools/gen_defaults.py")
            return 1
        print(f"  {len(read(SRC.read_text()))} defaults match .env.example")
        return 0
    OUT.write_text(want)
    print(f"  wrote data/{OUT.name} · {len(read(SRC.read_text()))} keys")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
